import os
stocks = ['AAPL', 'GOOGL', 'F', 'FB', 'AMD', 'MSFT', 'AEP', 'ALGN', 'IBM', 'TSLA', 'NFLX', 'GOOG', 'INTU', 'INTC', 'AMC', 'ZM', 
'TMUS', 'TXN', 'GME', 'EBAY', 'DDOG', 'AMZN', 'NOK', 'CCJ', 'CTXR', 'CMG', 'URG', 'ABNB', 'COST', 'ADBE', 'WEED', 'SBUX', 
'SIRI', 'PAYX', 'ORLY', 'NVDA', 'NTES', 'MU', 'MNST', 'MRNA', 'MCHP', 'MAR', 'KHZ', 'EXC', 'DLTR', 'WMT', 'TGT', 'ANSS', 
'TEAM', 'ADP', 'BKNG', 'PFE', 'PLTR', 'BBY', 'NAKD', 'BA', 'CERN', 'BJ', 'ROAD', 'NOVA', 'PLUM', 'DPLS', 'CSCO', 'CL', 
'DE', 'DIS', 'ATVI', 'SONY', 'MCD', 'QSR', 'MO', 'ENPH', 'WEN', 'NKE', 'YUM', 'EXPD', 'FDS', 'ILMN', 'SHAK', 'QCOM', 'ORCL', 
'EA', 'PEP', 'KO', 'LULU', 'SBX', 'TTWO', 'PYPL', 'VNMO', 'BAC', 'TD', 'C', 'JPM', 'DKNG', 'JNJ', 'CHWY', 'LZ', 'LVMH', 'MMM', 
'AOS', 'ABT', 'ABBV', 'ACN', 'ADM', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALLE', 'LNT', 'ALL', 'AMCR', 
'AEE', 'AAL', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'AON', 'APA', 'AMAT', 'APTV', 'ACGL', 'ANET', 
'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'AZO', 'AVB', 'AVY', 'BKR', 'BALL', 'BBWI', 'BAX', 'BDX', 'WRB', 'BIO', 'TECH', 'BIIB', 'BLK', 
'BK', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 
'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP', 'CDAY', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CB', 'CHD', 'CI', 
'CINF', 'CTAS', 'CFG', 'CLX', 'CME', 'CMS', 'CTSH', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 
'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISH', 'DG', 
'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DD', 'DXC', 'EMN', 'ETN', 'ECL', 'EIX', 'EW', 'ELV', 'LLY', 'EMR', 'ETR', 'EOG', 'EPAM', 
'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'RE', 'EVRG', 'ES', 'EXPE', 'EXR', 'XOM', 'FFIV', 'FAST', 'FRT', 'FDX', 'FITB', 
'FRC', 'FSLR', 'FE', 'FIS', 'FISV', 'FLT', 'FMC', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GEHC', 'GEN', 'GNRC', 
'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 
'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'ICE', 'IP', 'IPG', 
'IFF', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'JCI', 'JNPR', 'K', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 
'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LUMN', 
'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 
'MAA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NWL', 'NEM', 'NWSA', 'NWS', 
'NEE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVR', 'NXPI', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'OGN', 
'OTIS', 'PCAR', 'PKG', 'PARA', 'PH', 'PAYC', 'PNR', 'PKI', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 
'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'QRVO', 'PWR', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 
'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 
'SBNY', 'SPG', 'SWKS', 'SJM', 'SNA', 'SEDG', 'SO', 'LUV', 'SWK', 'STT', 'STLD', 'STE', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 
'TROW', 'TPR', 'TRGP', 'TEL', 'TDY', 'TFX', 'TER', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 
'TSN', 'USB', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 
'VTRS', 'VICI', 'V', 'VMC', 'WAB', 'WBA', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WHR', 
'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'ZBRA', 'ZBH', 'ZION', 'ZTS']
for symbol in stocks:
    os.system("node dist/main " + symbol)

os.system("py Trading/tradeStocks.py")